
export enum NotificationMessage {
    ENEMY_FIRE = 'ENEMY_FIRE',
    SPACECRAFT_FIRE_STRAIGHTLINE = 'SPACECRAFT_FIRE_STRAIGHTLINE',
    SPACECRAFT_FIRE_TRACKING = 'SPACECRAFT_FIRE_TRACKING',
    SPACECRAFT_FIRE_LASER = 'SPACECRAFT_FIRE_LASER',
    SET_PLAYER_CONTROLL = 'SET_PLAYER_CONTROLL',
}

