
export enum NotificationMessage {
    NONE = 'NONE',
    ENEMY_FIRE = 'ENEMY_FIRE',
    SPACECRAFT_FIRE_STRAIGHTLINE = 'SPACECRAFT_FIRE_STRAIGHTLINE',
    SPACECRAFT_FIRE_TRACKING = 'SPACECRAFT_FIRE_TRACKING',
    SPACECRAFT_FIRE_LASER = 'SPACECRAFT_FIRE_LASER',
    SPACECRAFT_MOVE = 'SPACECRAFT_MOVE',
    
    JOYSTICK_MOVE = 'JOYSTICK_MOVE',
    KEYBOARD_MOVE = 'KEYBOARD_MOVE',

    BROADCAST_ROOM_JOINROOM = 'BROADCAST_ROOM_JOINROOM',
    BROADCAST_ROOM_LEAVEROOM = 'BROADCAST_ROOM_LEAVEROOM',
    BROADCAST_ROOM_DISMISSROOM = 'BROADCAST_ROOM_DISMISSROOM',
    BROADCAST_ROOM_UPDATE = 'BROADCAST_ROOM_UPDATE',
    BROADCAST_ROOM_STARTFRAMESYNC = 'BROADCAST_ROOM_STARTFRAMESYNC',
    BROADCAST_ROOM_RECVFRAME = 'BROADCAST_ROOM_RECVFRAME',
    BROADCAST_ROOM_STOPFRAMESYNC = 'BROADCAST_ROOM_STOPFRAMESYNC',
}

export enum FrameMessage {
    JOYSTICK_MOVE = 'JOYSTICK_MOVE',
    KEYBOARD_MOVE = 'KEYBOARD_MOVE',
}

